name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

exclude-labels:
  - skip-release

autolabeler:
  - label: "feature"
    title: "/(Add|Adds|Create|New|Support|Implement)/i"
  - label: "fix"
    title: "/(fix|fixed)/i"
  - label: "documentation"
    title: "/(Doc|Docs)/i"
  - label: "housekeeping"
    title: "/(Clean|Update|Remove|Refactor|Redownload)/i"
  - label: "test"
    title: "/(test|testing)/i"

categories:
  - title: "🌟 New Features"
    labels:
      - feature
      - enhancement
  - title: "🔧 Fixed"
    labels:
      - fix
      - bugfix
  - title: "📖 Docs"
    labels:
      - documentation
  - title: "🧹 Tidying Up"
    labels:
      - housekeeping
      - refactor
  - title: "🎙️ Testing testing testing"
    labels:
      - test

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
  patch:
    labels:
      - patch
      - fix
  default: patch

template: |
  ## In the Latest Episode of `AO3.js`...

  $CHANGES
