/**
 * Post-processes schemas generated by ts-to-zod to fix enum handling: ts-to-zod
 * generates z.enum(EnumName) but Zod v3 requires z.nativeEnum(EnumName) for
 * TypeScript enums.
 */
import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const ENUM_PATTERN = /z\.enum\(([A-Z][a-zA-Z0-9]*)\)/g;

const schemasPath = resolve(import.meta.dirname, "generated/schemas.ts");
const content = readFileSync(schemasPath, "utf-8");
const fixedContent = content.replace(ENUM_PATTERN, "z.nativeEnum($1)");

const matches = content.match(ENUM_PATTERN);
if (matches) {
  console.log(`✔ Fixed ${matches.length} enum schemas to use z.nativeEnum()`);
}

writeFileSync(schemasPath, fixedContent);
console.log("✔ Generated types/zod/schemas.ts");
